//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u21593681_INF272HomeworkAss3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class borrows
    {
        [Key]
        public int borrowId { get; set; }
        
        [ForeignKey("studentId")]
        public Nullable<int> studentId { get; set; }

        [ForeignKey("bookId")]
        public Nullable<int> bookId { get; set; }

        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> takenDate { get; set; }
        
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> broughtDate { get; set; }
    
        public virtual books books { get; set; }
        public virtual students students { get; set; }
    }
}
